### ISSUE TITLE
Incompatibility with Package Control 4

### ISSUE THREAD

**Issue by wbond** [evandroforks/DiffMatchPatch#2]
The upcoming version of Package Control is restructuring how dependencies work, to allow for supporting both Python 3.3 and Python 3.8.

Due to the way this module doesn't use the standard folder layout and instead has a custom `loader.code`, it and all dependent packages will break when Package Control 4 is released. That will likely happen in the next week or so.

I recommend switching it to put `diffmatchpath.py` in a folder named `st3` instead of `python3`. There will be nothing analogous to `loader.code` in the new version of dependencies. They will all be installed directly in the `{DATA_DIR}/Lib/python33/` folder and normal Python import mechanisms will pick them up.

**Comment by evandrocoan** [comment]
Thanks for reporting it! I pushed a fix for it.
